# -*- coding: utf-8 -*-
"""syndicai

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vzs5PaV7xijxVyYkOVPG0P2FZxoikNRx
"""

import torch
from PIL import Image 


class PythonPredictor:

    def __init__(self, config):
        """ Download pretrained model. """
        #self.model = torch.hub.load('MariaGeorge55/Defect-inspection', 'model_scripted_defect.pt', pretrained=True)#.autoshape()
        #self.model = torch.jit.load('https://github.com/MariaGeorge55/Defect-inspection/blob/main/model_scripted_defect.pt')#.autoshape()

        self.model = torch.jit.load('MariaGeorge55/Defect-inspection/model_scripted_defect.pt').autoshape()

    def predict(self, img):
        """ Run a model based on url input. """

        # Inference
        #img = url_to_img(payload["url"])
        outputs = self.model(img)
        _, preds = torch.max(outputs, 1)
        pred = preds.cpu()
        
        return pred  #img_to_bytes(box_img)

